info:
  component: Turbine

server:
  port: 8989

management:
  port: 8990

logging:
  level:
    root: INFO
    com.netflix.discovery: 'OFF'
    # org.springframework.integration: DEBUG

turbine:
  appConfig: calculator,currency
  clusterNameExpression: new String('default')
  combineHostPort: true